// src/components/md/renderers/code.tsx
import React from "react";
import Highlight, { defaultProps } from "prism-react-renderer";
import theme from "prism-react-renderer/themes/dracula";

const RE = /{([\d,-]+)}/;

function calculateLinesToHighlight(meta) {
  if (RE.test(meta)) {
    const lineNumbers = RE.exec(meta)[1]
      .split(",")
      .map((v) => v.split("-").map((y) => parseInt(y, 10)));
    return (index) => {
      const lineNumber = index + 1;
      const inRange = lineNumbers.some(([start, end]) =>
        end ? lineNumber >= start && lineNumber <= end : lineNumber === start
      );
      return inRange;
    };
  } else {
    return () => false;
  }
}

export default ({ children, className, metastring, ...props }) => {
  const language = className.replace(/language-/, "");
  const shouldHighlightLine = calculateLinesToHighlight(metastring);
  return (
    <Highlight
      {...defaultProps}
      code={children}
      language={language}
      theme={theme}
      {...props}
    >
      {({ className, style, tokens, getLineProps, getTokenProps }) => {
        tokens.pop(); //This might reveal to be a bug later on.
        return (
          <div className="my-4">
            <pre
              className={className}
              style={{
                ...style,
                padding: "4px 0px",
                fontSize: "14px",
                borderRadius: "4px",
                overflowX: 'auto',
              }}
            >
              {tokens.map((line, i) => {
                const lineProps = getLineProps({ line, key: i });
                if (shouldHighlightLine(i)) {
                  lineProps.className = `${lineProps.className} highlight-line pl-2`;
                } else {
                  lineProps.className = `${lineProps.className} border-l-2 border-transparent pl-2`;
                }
                return (
                  <div key={i} {...lineProps}>
                    <span
                      style={{
                        display: "inline-block",
                        width: "2em",
                        userSelect: "none",
                        opacity: 0.3,
                      }}
                    >
                      {i + 1}
                    </span>
                    {line.map((token, key) => (
                      <span key={key} {...getTokenProps({ token, key })} />
                    ))}
                  </div>
                );
              })}
            </pre>
          </div>
        );
      }}
    </Highlight>
  );
};

// src/lib/Blog/Renderers/Code.svelte
<script>
	import { marked } from 'marked';
	import Prism from 'prismjs';
	export let code = '';
	export let infostring = '';
	export let escaped = false;
	export let lang;
	export let text;
	export let raw;

	const RE = /{([\d,-]+)}/;

	function calculateLinesToHighlight(meta) {
		if (RE.test(meta)) {
			const lineNumbers = RE.exec(meta)[1]
				.split(',')
				.map((v) => v.split('-').map((y) => parseInt(y, 10)));
			return (index) => {
				const lineNumber = index + 1;
				const inRange = lineNumbers.some(([start, end]) =>
					end ? lineNumber >= start && lineNumber <= end : lineNumber === start
				);
				return inRange;
			};
		} else {
			return () => false;
		}
	}

	const html = marked
		.walkTokens(marked.lexer(raw), (token) => {
			const shouldHighlightLine = calculateLinesToHighlight(token.lang);
			return text.split('\n').map((line, i) => {
				const html = `<span class="line-number"  data-line-number=${i + 1}></span>${Prism.highlight(
					line,
					Prism.languages['javascript']
				)}</div>`;
				// return html;
				return `<div class="code-line ${
					shouldHighlightLine(i) ? 'highlight-line' : ''
				}">${html}</div>`;
			});
		})
		.reduce((acc, line) => `${acc ? `${acc}\n` : acc}${line}`, '');
</script>

<pre class="bg-slate-900 py-4 px-2 my-4 text-gray-50 rounded-lg overflow-x-auto text-base">
	<code>
		{@html html}
	</code>
</pre>

<style lang="postcss">
	pre,
	code {
		font-family: MonoLisa, Consolas, Monaco, monospace;
	}
	.code-line {
		display: inline-block;
		width: 100%;
		margin: 0;
		padding: 0;
	}
</style>
