// src/lib/Blog/CustomRenderers/Code.svelte
<script>
	import { marked } from 'marked';
	import Prism from 'prismjs';
	// export let code = '';
	// export let infostring = '';
	// export let escaped = false;
	// export let lang;
	export let text;
	export let raw;

	const RE = /{([\d,-]+)}/;

	function calculateLinesToHighlight(meta) {
		if (RE.test(meta)) {
			const lineNumbers = RE.exec(meta)[1]
				.split(',')
				.map((v) => v.split('-').map((y) => parseInt(y, 10)));
			return (index) => {
				const lineNumber = index + 1;
				const inRange = lineNumbers.some(([start, end]) =>
					end ? lineNumber >= start && lineNumber <= end : lineNumber === start
				);
				return inRange;
			};
		} else {
			return () => false;
		}
	}

	const html = marked
		.walkTokens(marked.lexer(raw), (token) => {
			const lang = token.lang.split(' ')[0] ?? 'txt';
			// console.log(lang)
			const shouldHighlightLine = calculateLinesToHighlight(lang);
			return text.split('\n').map((line, i) => {
				const html = `<span class="line-number"  data-line-number=${i + 1}></span>${Prism.highlight(
					line,
					Prism.languages[lang]
				)}`;
				// return html;
				return `<div class="code-line ${
					shouldHighlightLine(i) ? 'highlight-line' : ''
				}">${html}</div>`;
			});
		})
		.reduce((acc, line) => `${acc ? `${acc}\n` : acc}${line}`, '');

</script>

<pre class="bg-slate-900 py-4 px-2 my-4 text-gray-50 rounded-lg overflow-x-auto text-base"><code>{@html html}</code></pre>

<style lang="postcss">
	pre,
	code {
		font-family: MonoLisa, Consolas, Monaco, monospace;
	}
	.code-line {
		display: inline-block;
		width: 100%;
		margin: 0;
		padding: 0;
	}
</style>

// src/components/mdx/code.tsx
import React from "react";
import theme from "prism-react-renderer/themes/nightOwl";
/* import {bpDesktopOnly} from '../../lib/breakpoints' */
import Highlight, { defaultProps } from "prism-react-renderer";

const RE = /{([\d,-]+)}/;

/* const wrapperStyles = css`
  overflow: auto;
  margin-left: -20px;
  margin-right: -20px;
  ${bpDesktopOnly} {
    margin-left: -80px;
    margin-right: -80px;
  }
` */

/* const preStyles = css`
  float: left;
  min-width: 100%;
  overflow: initial;
` */

function calculateLinesToHighlight(meta) {
  if (RE.test(meta)) {
    const lineNumbers = RE.exec(meta)[1]
      .split(",")
      .map((v) => v.split("-").map((y) => parseInt(y, 10)));
    return (index) => {
      const lineNumber = index + 1;
      const inRange = lineNumbers.some(([start, end]) =>
        end ? lineNumber >= start && lineNumber <= end : lineNumber === start
      );
      return inRange;
    };
  } else {
    return () => false;
  }
}

function Code({ codeString, language, metastring }) {
  const shouldHighlightLine = calculateLinesToHighlight(metastring);
  return (
    <Highlight
      {...defaultProps}
      code={codeString}
      language={language}
      theme={theme}
    >
      {({ className, style, tokens, getLineProps, getTokenProps }) => (
        <div className="overflow-auto">
          <pre className={`${className} float-left min-w-full`} style={style}>
            {tokens.map((line, i) => (
              <div
                key={i}
                {...getLineProps({
                  line,
                  key: i,
                  className: shouldHighlightLine(i) ? "highlight-line" : "",
                })}
              >
                <span
                /* css={css`
                    display: inline-block;
                    width: 2em;
                    user-select: none;
                    opacity: 0.3;
                  `} */
                >
                  {i + 1}
                </span>
                {line.map((token, key) => (
                  <span key={key} {...getTokenProps({ token, key })} />
                ))}
              </div>
            ))}
          </pre>
        </div>
      )}
    </Highlight>
  );
}

export default Code;
