// src/components/md/CoverImage.tsx
export default function CoverImage({ title, src, slug, accreditation }) {
  return (
    <div
      className="flex justify-center flex-col"
      style={{ backgroundColor: "hsl(200,100%,4%)" }}
    >
      <img
        src={src}
        alt={`Cover Image for ${title}`}
        loading="lazy"
        className="pb-0"
      />
      <em className="text-base text-gray-400">
        Photo by <span className="underline">{accreditation}</span> on <a href={src}>Unplash</a>
      </em>
    </div>
  );
}

// src/lib/Blog/CoverImage.svelte
<script>
	export let accreditation;
	export let src;
	export let title;
</script>

<div class="flex justify-center flex-col">
	<img {src} alt={`Cover Image for ${title}`} loading="lazy" class="pb-0" />
	<em class="text-base text-gray-400">
		<!-- {t('coverImage_pictureBy')}{' '} -->
		picture by
		<a class="underline" href={src}>
			{accreditation}
		</a>{' '}
		<!-- {t('coverImage_on')}{' '} -->cover image
		<a class="underline" href={src}> Unplash </a>
	</em>
</div>

<style>
	div {
		background-color: hsl(200, 100%, 4%);
	}
</style>
